---
- name: Update apt cache
  apt:
    update_cache: yes


- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Remove unnecessary packages
  apt:
    autoremove: yes

- name: Clean up the local repository of retrieved package files
  apt:
    autoclean: yes

- name: Install UFW
  apt:
    name:
      - ufw
    state: present

- name: Allow OpenSSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  ufw:
    state: enabled

- name: Disable password authentication in SSH config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication\s+'
    line: 'PasswordAuthentication no'
    state: present
  notify: restart_ssh
